#!/usr/bin/env python3
"""
中国教材词库生成器
生成初中、高中、CET4、CET6词库
"""

import json
import os

# 词库保存路径
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'words', 'china')

# 初中词库 (1000词) - 基于人教版初中英语教材核心词汇
JUNIOR_WORDS = [
    ("ability", "əˈbɪləti", "n", "能力", "skill or power"),
    ("able", "ˈeɪbl", "adj", "能够的", "having the power"),
    ("about", "əˈbaʊt", "prep", "关于", "concerning"),
    ("above", "əˈbʌv", "prep", "在...上面", "higher than"),
    ("abroad", "əˈbrɔːd", "adv", "在国外", "in a foreign country"),
    ("absent", "ˈæbsənt", "adj", "缺席的", "not present"),
    ("accept", "əkˈsept", "v", "接受", "receive willingly"),
    ("accident", "ˈæksɪdənt", "n", "事故", "unexpected event"),
    ("achieve", "əˈtʃiːv", "v", "实现", "succeed in"),
    ("across", "əˈkrɒs", "prep", "穿过", "from one side to other"),
    ("act", "ækt", "v", "行动", "do something"),
    ("action", "ˈækʃn", "n", "行动", "the process of doing"),
    ("active", "ˈæktɪv", "adj", "积极的", "energetic"),
    ("activity", "ækˈtɪvəti", "n", "活动", "thing to do"),
    ("actor", "ˈæktər", "n", "演员", "person who acts"),
    ("actress", "ˈæktrəs", "n", "女演员", "female actor"),
    ("actual", "ˈæktʃuəl", "adj", "实际的", "real"),
    ("actually", "ˈæktʃuəli", "adv", "实际上", "in fact"),
    ("add", "æd", "v", "添加", "put together"),
    ("address", "əˈdres", "n", "地址", "location"),
    ("admire", "ədˈmaɪər", "v", "钦佩", "respect greatly"),
    ("admit", "ədˈmɪt", "v", "承认", "accept as true"),
    ("adult", "ˈædʌlt", "n", "成年人", "grown person"),
    ("advantage", "ədˈvɑːntɪdʒ", "n", "优势", "benefit"),
    ("adventure", "ədˈventʃər", "n", "冒险", "exciting experience"),
    ("advertise", "ˈædvərtaɪz", "v", "做广告", "promote publicly"),
    ("advice", "ədˈvaɪs", "n", "建议", "guidance"),
    ("advise", "ədˈvaɪz", "v", "建议", "give advice"),
    ("affair", "əˈfeər", "n", "事务", "matter"),
    ("affect", "əˈfekt", "v", "影响", "have effect on"),
    ("afford", "əˈfɔːrd", "v", "负担得起", "have enough money"),
    ("afraid", "əˈfreɪd", "adj", "害怕的", "scared"),
    ("after", "ˈɑːftər", "prep", "在...之后", "following"),
    ("afternoon", "ˌɑːftərˈnuːn", "n", "下午", "after midday"),
    ("again", "əˈɡen", "adv", "再次", "once more"),
    ("against", "əˈɡenst", "prep", "反对", "opposed to"),
    ("age", "eɪdʒ", "n", "年龄", "how old"),
    ("agent", "ˈeɪdʒənt", "n", "代理人", "representative"),
    ("ago", "əˈɡoʊ", "adv", "以前", "in the past"),
    ("agree", "əˈɡriː", "v", "同意", "have same opinion"),
    ("agreement", "əˈɡriːmənt", "n", "协议", "arrangement"),
    ("ahead", "əˈhed", "adv", "在前面", "in front"),
    ("aim", "eɪm", "n", "目标", "goal"),
    ("air", "eər", "n", "空气", "atmosphere"),
    ("airline", "ˈeərlaɪn", "n", "航空公司", "air transport company"),
    ("airplane", "ˈeərpleɪn", "n", "飞机", "aircraft"),
    ("airport", "ˈeərpɔːrt", "n", "机场", "place for planes"),
    ("alarm", "əˈlɑːrm", "n", "警报", "warning signal"),
    ("album", "ˈælbəm", "n", "相册", "photo book"),
    ("alike", "əˈlaɪk", "adj", "相似的", "similar"),
    ("alive", "əˈlaɪv", "adj", "活着的", "living"),
    ("all", "ɔːl", "det", "所有的", "every one"),
    ("allow", "əˈlaʊ", "v", "允许", "permit"),
    ("almost", "ˈɔːlmoʊst", "adv", "几乎", "nearly"),
    ("alone", "əˈloʊn", "adj", "独自的", "by oneself"),
    ("along", "əˈlɔːŋ", "prep", "沿着", "beside"),
    ("already", "ɔːlˈredi", "adv", "已经", "before now"),
    ("also", "ˈɔːlsoʊ", "adv", "也", "too"),
    ("although", "ɔːlˈðoʊ", "conj", "虽然", "even though"),
    ("always", "ˈɔːlweɪz", "adv", "总是", "at all times"),
    ("amazing", "əˈmeɪzɪŋ", "adj", "令人惊叹的", "wonderful"),
    ("among", "əˈmʌŋ", "prep", "在...之中", "in the middle of"),
    ("amount", "əˈmaʊnt", "n", "数量", "quantity"),
    ("ancient", "ˈeɪnʃənt", "adj", "古老的", "very old"),
    ("and", "ænd", "conj", "和", "also"),
    ("anger", "ˈæŋɡər", "n", "愤怒", "strong displeasure"),
    ("angry", "ˈæŋɡri", "adj", "生气的", "feeling anger"),
    ("animal", "ˈænɪml", "n", "动物", "living creature"),
    ("announce", "əˈnaʊns", "v", "宣布", "make known"),
    ("another", "əˈnʌðər", "det", "另一个", "one more"),
    ("answer", "ˈænsər", "n", "答案", "reply"),
    ("ant", "ænt", "n", "蚂蚁", "small insect"),
    ("anxious", "ˈæŋkʃəs", "adj", "焦虑的", "worried"),
    ("any", "ˈeni", "det", "任何", "some"),
    ("anybody", "ˈenibɒdi", "pron", "任何人", "any person"),
    ("anyone", "ˈeniwʌn", "pron", "任何人", "anybody"),
    ("anything", "ˈeniθɪŋ", "pron", "任何事物", "any thing"),
    ("anyway", "ˈeniweɪ", "adv", "无论如何", "in any case"),
    ("anywhere", "ˈeniweər", "adv", "任何地方", "any place"),
    ("apartment", "əˈpɑːrtmənt", "n", "公寓", "flat"),
    ("apologize", "əˈpɒlədʒaɪz", "v", "道歉", "say sorry"),
    ("appear", "əˈpɪr", "v", "出现", "come into view"),
    ("appearance", "əˈpɪrəns", "n", "外表", "how one looks"),
    ("apple", "ˈæpl", "n", "苹果", "red fruit"),
    ("application", "ˌæplɪˈkeɪʃn", "n", "申请", "formal request"),
    ("apply", "əˈplaɪ", "v", "申请", "make request"),
    ("appreciate", "əˈpriːʃieɪt", "v", "欣赏", "value highly"),
    ("approach", "əˈproʊtʃ", "v", "接近", "come near"),
    ("appropriate", "əˈproʊpriət", "adj", "适当的", "suitable"),
    ("area", "ˈeəriə", "n", "区域", "region"),
    ("argue", "ˈɑːrɡjuː", "v", "争论", "disagree"),
    ("argument", "ˈɑːrɡjumənt", "n", "争论", "disagreement"),
    ("arm", "ɑːrm", "n", "手臂", "body part"),
    ("army", "ˈɑːrmi", "n", "军队", "military force"),
    ("around", "əˈraʊnd", "prep", "周围", "surrounding"),
    ("arrange", "əˈreɪndʒ", "v", "安排", "organize"),
    ("arrangement", "əˈreɪndʒmənt", "n", "安排", "plan"),
    ("arrive", "əˈraɪv", "v", "到达", "reach destination"),
    ("art", "ɑːrt", "n", "艺术", "creative work"),
    ("article", "ˈɑːrtɪkl", "n", "文章", "piece of writing"),
    ("artist", "ˈɑːrtɪst", "n", "艺术家", "creative person"),
    ("as", "æz", "conj", "作为", "in the role of"),
    ("ashamed", "əˈʃeɪmd", "adj", "羞愧的", "feeling shame"),
    ("Asia", "ˈeɪʒə", "n", "亚洲", "continent"),
    ("Asian", "ˈeɪʒn", "adj", "亚洲的", "from Asia"),
    ("ask", "æsk", "v", "问", "request info"),
    ("asleep", "əˈsliːp", "adj", "睡着的", "sleeping"),
    ("assistant", "əˈsɪstənt", "n", "助手", "helper"),
    ("assume", "əˈsuːm", "v", "假设", "suppose"),
    ("at", "æt", "prep", "在", "location"),
    ("athlete", "ˈæθliːt", "n", "运动员", "sportsperson"),
    ("attack", "əˈtæk", "v", "攻击", "assault"),
    ("attempt", "əˈtempt", "v", "尝试", "try"),
    ("attend", "əˈtend", "v", "参加", "be present at"),
    ("attention", "əˈtenʃn", "n", "注意", "focus"),
    ("attitude", "ˈætɪtjuːd", "n", "态度", "way of thinking"),
    ("attract", "əˈtrækt", "v", "吸引", "draw attention"),
    ("attractive", "əˈtræktɪv", "adj", "有吸引力的", "appealing"),
    ("audience", "ˈɔːdiəns", "n", "观众", "viewers"),
    ("aunt", "ɑːnt", "n", "阿姨", "parent's sister"),
    ("author", "ˈɔːθər", "n", "作者", "writer"),
    ("autumn", "ˈɔːtəm", "n", "秋天", "fall season"),
    ("available", "əˈveɪləbl", "adj", "可用的", "accessible"),
    ("average", "ˈævərɪdʒ", "adj", "平均的", "typical"),
    ("avoid", "əˈvɔɪd", "v", "避免", "keep away from"),
    ("awake", "əˈweɪk", "adj", "醒着的", "not sleeping"),
    ("award", "əˈwɔːrd", "n", "奖励", "prize"),
    ("aware", "əˈweər", "adj", "意识到的", "conscious of"),
    ("away", "əˈweɪ", "adv", "离开", "at a distance"),
    ("awful", "ˈɔːfl", "adj", "糟糕的", "very bad"),
    ("baby", "ˈbeɪbi", "n", "婴儿", "infant"),
    ("back", "bæk", "n", "背部", "rear part"),
    ("background", "ˈbækɡraʊnd", "n", "背景", "setting"),
    ("backward", "ˈbækwərd", "adv", "向后", "to the rear"),
    ("bad", "bæd", "adj", "坏的", "not good"),
    ("badly", "ˈbædli", "adv", "严重地", "poorly"),
    ("bag", "bæɡ", "n", "包", "container"),
    ("bake", "beɪk", "v", "烘焙", "cook in oven"),
    ("balance", "ˈbæləns", "n", "平衡", "stability"),
    ("ball", "bɔːl", "n", "球", "round object"),
    ("balloon", "bəˈluːn", "n", "气球", "inflatable toy"),
    ("ban", "bæn", "v", "禁止", "forbid"),
    ("banana", "bəˈnænə", "n", "香蕉", "yellow fruit"),
    ("band", "bænd", "n", "乐队", "music group"),
    ("bank", "bæŋk", "n", "银行", "financial institution"),
    ("bar", "bɑːr", "n", "酒吧", "drinking place"),
    ("base", "beɪs", "n", "基础", "foundation"),
    ("basic", "ˈbeɪsɪk", "adj", "基本的", "fundamental"),
    ("basket", "ˈbɑːskɪt", "n", "篮子", "container"),
    ("basketball", "ˈbɑːskɪtbɔːl", "n", "篮球", "sport"),
    ("bat", "bæt", "n", "蝙蝠", "flying mammal"),
    ("bath", "bɑːθ", "n", "洗澡", "washing"),
    ("bathroom", "ˈbɑːθruːm", "n", "浴室", "washing room"),
    ("battery", "ˈbætəri", "n", "电池", "power source"),
    ("battle", "ˈbætl", "n", "战斗", "fight"),
    ("be", "biː", "v", "是", "exist"),
    ("beach", "biːtʃ", "n", "海滩", "sandy shore"),
    ("bean", "biːn", "n", "豆子", "seed vegetable"),
    ("bear", "beər", "n", "熊", "large animal"),
    ("beat", "biːt", "v", "打败", "defeat"),
    ("beautiful", "ˈbjuːtɪfl", "adj", "美丽的", "attractive"),
    ("beauty", "ˈbjuːti", "n", "美丽", "attractiveness"),
    ("became", "bɪˈkeɪm", "v", "成为(过去式)", "past of become"),
    ("because", "bɪˈkɔːz", "conj", "因为", "for the reason"),
    ("become", "bɪˈkʌm", "v", "成为", "come to be"),
    ("bed", "bed", "n", "床", "furniture for sleeping"),
    ("bedroom", "ˈbedruːm", "n", "卧室", "sleeping room"),
    ("beef", "biːf", "n", "牛肉", "cow meat"),
    ("been", "biːn", "v", "是(过去分词)", "past participle of be"),
    ("beer", "bɪr", "n", "啤酒", "alcoholic drink"),
    ("before", "bɪˈfɔːr", "prep", "在...之前", "earlier than"),
    ("begin", "bɪˈɡɪn", "v", "开始", "start"),
    ("beginning", "bɪˈɡɪnɪŋ", "n", "开始", "start"),
    ("behave", "bɪˈheɪv", "v", "表现", "act"),
    ("behavior", "bɪˈheɪvjər", "n", "行为", "conduct"),
    ("behind", "bɪˈhaɪnd", "prep", "在...后面", "at the back of"),
    ("belief", "bɪˈliːf", "n", "信念", "trust"),
    ("believe", "bɪˈliːv", "v", "相信", "trust"),
    ("bell", "bel", "n", "铃", "ringing device"),
    ("belong", "bɪˈlɔːŋ", "v", "属于", "be owned by"),
    ("below", "bɪˈloʊ", "prep", "在...下面", "lower than"),
    ("belt", "belt", "n", "皮带", "waist band"),
    ("bench", "bentʃ", "n", "长凳", "seat"),
    ("bend", "bend", "v", "弯曲", "curve"),
    ("benefit", "ˈbenɪfɪt", "n", "益处", "advantage"),
    ("beside", "bɪˈsaɪd", "prep", "在...旁边", "next to"),
    ("besides", "bɪˈsaɪdz", "prep", "除...之外", "in addition to"),
    ("best", "best", "adj", "最好的", "most good"),
    ("better", "ˈbetər", "adj", "更好的", "more good"),
    ("between", "bɪˈtwiːn", "prep", "在...之间", "in the middle"),
    ("beyond", "bɪˈjɒnd", "prep", "超越", "further than"),
    ("bicycle", "ˈbaɪsɪkl", "n", "自行车", "two-wheeled vehicle"),
    ("big", "bɪɡ", "adj", "大的", "large"),
    ("bike", "baɪk", "n", "自行车", "bicycle"),
    ("bill", "bɪl", "n", "账单", "statement of charges"),
    ("billion", "ˈbɪljən", "num", "十亿", "1000 million"),
    ("bird", "bɜːrd", "n", "鸟", "flying animal"),
    ("birth", "bɜːrθ", "n", "出生", "being born"),
    ("birthday", "ˈbɜːrθdeɪ", "n", "生日", "anniversary of birth"),
    ("bit", "bɪt", "n", "一点", "small amount"),
    ("bite", "baɪt", "v", "咬", "cut with teeth"),
    ("bitter", "ˈbɪtər", "adj", "苦的", "not sweet"),
    ("black", "blæk", "adj", "黑色的", "darkest color"),
    ("blame", "bleɪm", "v", "责备", "hold responsible"),
    ("blank", "blæŋk", "adj", "空白的", "empty"),
    ("blanket", "ˈblæŋkɪt", "n", "毯子", "bed cover"),
    ("blind", "blaɪnd", "adj", "盲的", "cannot see"),
    ("block", "blɒk", "n", "街区", "area of buildings"),
    ("blood", "blʌd", "n", "血", "red liquid in body"),
    ("blow", "bloʊ", "v", "吹", "move air"),
    ("blue", "bluː", "adj", "蓝色的", "sky color"),
    ("board", "bɔːrd", "n", "木板", "flat piece"),
    ("boat", "boʊt", "n", "船", "water vehicle"),
    ("body", "ˈbɒdi", "n", "身体", "physical form"),
    ("boil", "bɔɪl", "v", "煮沸", "heat to bubbling"),
    ("bomb", "bɒm", "n", "炸弹", "explosive"),
    ("bone", "boʊn", "n", "骨头", "skeleton part"),
    ("book", "bʊk", "n", "书", "written work"),
    ("boot", "buːt", "n", "靴子", "footwear"),
    ("border", "ˈbɔːrdər", "n", "边界", "boundary"),
    ("bored", "bɔːrd", "adj", "无聊的", "not interested"),
    ("boring", "ˈbɔːrɪŋ", "adj", "无聊的", "not interesting"),
    ("born", "bɔːrn", "adj", "出生的", "brought into life"),
    ("borrow", "ˈbɒroʊ", "v", "借入", "take temporarily"),
    ("boss", "bɒs", "n", "老板", "employer"),
    ("both", "boʊθ", "det", "两个都", "the two"),
    ("bother", "ˈbɒðər", "v", "打扰", "annoy"),
    ("bottle", "ˈbɒtl", "n", "瓶子", "container"),
    ("bottom", "ˈbɒtəm", "n", "底部", "lowest part"),
    ("bowl", "boʊl", "n", "碗", "round dish"),
    ("box", "bɒks", "n", "盒子", "container"),
    ("boy", "bɔɪ", "n", "男孩", "male child"),
    ("brain", "breɪn", "n", "大脑", "thinking organ"),
    ("branch", "bræntʃ", "n", "树枝", "part of tree"),
    ("brand", "brænd", "n", "品牌", "product name"),
    ("brave", "breɪv", "adj", "勇敢的", "courageous"),
    ("bread", "bred", "n", "面包", "baked food"),
    ("break", "breɪk", "v", "打破", "damage"),
    ("breakfast", "ˈbrekfəst", "n", "早餐", "morning meal"),
    ("breast", "brest", "n", "胸部", "chest"),
    ("breath", "breθ", "n", "呼吸", "air inhaled"),
    ("breathe", "briːð", "v", "呼吸", "inhale and exhale"),
    ("bridge", "brɪdʒ", "n", "桥", "crossing structure"),
    ("brief", "briːf", "adj", "简短的", "short"),
    ("bright", "braɪt", "adj", "明亮的", "full of light"),
    ("brilliant", "ˈbrɪliənt", "adj", "杰出的", "very clever"),
    ("bring", "brɪŋ", "v", "带来", "carry to"),
    ("broad", "brɔːd", "adj", "宽的", "wide"),
    ("broadcast", "ˈbrɔːdkɑːst", "v", "广播", "transmit"),
    ("brother", "ˈbrʌðər", "n", "兄弟", "male sibling"),
    ("brown", "braʊn", "adj", "棕色的", "earth color"),
    ("brush", "brʌʃ", "n", "刷子", "cleaning tool"),
    ("bucket", "ˈbʌkɪt", "n", "水桶", "container"),
    ("build", "bɪld", "v", "建造", "construct"),
    ("building", "ˈbɪldɪŋ", "n", "建筑物", "structure"),
    ("burn", "bɜːrn", "v", "燃烧", "be on fire"),
    ("burst", "bɜːrst", "v", "爆裂", "break open"),
    ("bury", "ˈberi", "v", "埋葬", "put underground"),
    ("bus", "bʌs", "n", "公共汽车", "large vehicle"),
    ("business", "ˈbɪznəs", "n", "生意", "commerce"),
    ("busy", "ˈbɪzi", "adj", "忙碌的", "having much to do"),
    ("but", "bʌt", "conj", "但是", "however"),
    ("butter", "ˈbʌtər", "n", "黄油", "dairy product"),
    ("button", "ˈbʌtn", "n", "按钮", "fastener"),
    ("buy", "baɪ", "v", "买", "purchase"),
    ("by", "baɪ", "prep", "通过", "near"),
    ("cabbage", "ˈkæbɪdʒ", "n", "卷心菜", "vegetable"),
    ("cable", "ˈkeɪbl", "n", "电缆", "wire"),
    ("cafe", "kæˈfeɪ", "n", "咖啡馆", "coffee shop"),
    ("cage", "keɪdʒ", "n", "笼子", "enclosure"),
    ("cake", "keɪk", "n", "蛋糕", "sweet dessert"),
    ("calculate", "ˈkælkjuleɪt", "v", "计算", "work out"),
    ("calendar", "ˈkæləndər", "n", "日历", "date chart"),
    ("call", "kɔːl", "v", "打电话", "phone"),
    ("calm", "kɑːm", "adj", "平静的", "peaceful"),
    ("camera", "ˈkæmərə", "n", "相机", "photo device"),
    ("camp", "kæmp", "n", "营地", "outdoor site"),
    ("campaign", "kæmˈpeɪn", "n", "运动", "organized effort"),
    ("campus", "ˈkæmpəs", "n", "校园", "school grounds"),
    ("can", "kæn", "v", "能", "be able to"),
    ("cancel", "ˈkænsl", "v", "取消", "call off"),
    ("cancer", "ˈkænsər", "n", "癌症", "disease"),
    ("candidate", "ˈkændɪdeɪt", "n", "候选人", "applicant"),
    ("candle", "ˈkændl", "n", "蜡烛", "wax light"),
    ("candy", "ˈkændi", "n", "糖果", "sweet"),
    ("cap", "kæp", "n", "帽子", "head covering"),
    ("capital", "ˈkæpɪtl", "n", "首都", "main city"),
    ("captain", "ˈkæptɪn", "n", "队长", "leader"),
    ("capture", "ˈkæptʃər", "v", "捕获", "catch"),
    ("car", "kɑːr", "n", "汽车", "vehicle"),
    ("card", "kɑːrd", "n", "卡片", "paper card"),
    ("care", "keər", "v", "关心", "look after"),
    ("career", "kəˈrɪr", "n", "职业", "profession"),
    ("careful", "ˈkeərfl", "adj", "小心的", "cautious"),
    ("carefully", "ˈkeərfəli", "adv", "小心地", "with care"),
    ("careless", "ˈkeərləs", "adj", "粗心的", "not careful"),
    ("carpet", "ˈkɑːrpɪt", "n", "地毯", "floor covering"),
    ("carrot", "ˈkærət", "n", "胡萝卜", "orange vegetable"),
    ("carry", "ˈkæri", "v", "携带", "transport"),
    ("cartoon", "kɑːrˈtuːn", "n", "卡通", "animated show"),
    ("case", "keɪs", "n", "情况", "instance"),
    ("cash", "kæʃ", "n", "现金", "money"),
    ("castle", "ˈkɑːsl", "n", "城堡", "fortress"),
    ("cat", "kæt", "n", "猫", "pet animal"),
    ("catch", "kætʃ", "v", "抓住", "capture"),
    ("category", "ˈkætəɡɔːri", "n", "类别", "group"),
    ("cattle", "ˈkætl", "n", "牛群", "cows"),
    ("cause", "kɔːz", "v", "引起", "make happen"),
    ("cave", "keɪv", "n", "洞穴", "underground space"),
    ("ceiling", "ˈsiːlɪŋ", "n", "天花板", "room top"),
    ("celebrate", "ˈseləbreɪt", "v", "庆祝", "honor"),
    ("celebration", "ˌseləˈbreɪʃn", "n", "庆祝", "festivity"),
    ("cell", "sel", "n", "细胞", "basic unit"),
    ("cent", "sent", "n", "分", "coin"),
    ("center", "ˈsentər", "n", "中心", "middle"),
    ("central", "ˈsentrəl", "adj", "中心的", "main"),
    ("century", "ˈsentʃəri", "n", "世纪", "100 years"),
    ("ceremony", "ˈserəmoʊni", "n", "典礼", "formal event"),
    ("certain", "ˈsɜːrtn", "adj", "确定的", "sure"),
    ("certainly", "ˈsɜːrtnli", "adv", "当然", "definitely"),
    ("chain", "tʃeɪn", "n", "链条", "connected links"),
    ("chair", "tʃeər", "n", "椅子", "seat"),
    ("chairman", "ˈtʃeərmən", "n", "主席", "leader"),
    ("challenge", "ˈtʃælɪndʒ", "n", "挑战", "difficult task"),
    ("champion", "ˈtʃæmpiən", "n", "冠军", "winner"),
    ("chance", "tʃæns", "n", "机会", "opportunity"),
    ("change", "tʃeɪndʒ", "v", "改变", "make different"),
    ("channel", "ˈtʃænl", "n", "频道", "TV station"),
    ("chapter", "ˈtʃæptər", "n", "章节", "book section"),
    ("character", "ˈkærəktər", "n", "人物", "person"),
    ("charge", "tʃɑːrdʒ", "v", "收费", "ask payment"),
    ("charity", "ˈtʃærəti", "n", "慈善", "giving help"),
    ("charm", "tʃɑːrm", "n", "魅力", "attraction"),
    ("chart", "tʃɑːrt", "n", "图表", "diagram"),
    ("chase", "tʃeɪs", "v", "追赶", "run after"),
    ("chat", "tʃæt", "v", "聊天", "talk casually"),
    ("cheap", "tʃiːp", "adj", "便宜的", "low price"),
    ("cheat", "tʃiːt", "v", "作弊", "deceive"),
    ("check", "tʃek", "v", "检查", "examine"),
    ("cheek", "tʃiːk", "n", "脸颊", "face side"),
    ("cheer", "tʃɪr", "v", "欢呼", "shout support"),
    ("cheerful", "ˈtʃɪrfl", "adj", "快乐的", "happy"),
    ("cheese", "tʃiːz", "n", "奶酪", "dairy product"),
    ("chef", "ʃef", "n", "厨师", "cook"),
    ("chemical", "ˈkemɪkl", "adj", "化学的", "of chemistry"),
    ("chemistry", "ˈkemɪstri", "n", "化学", "science"),
    ("chess", "tʃes", "n", "国际象棋", "board game"),
    ("chest", "tʃest", "n", "胸部", "body part"),
    ("chicken", "ˈtʃɪkɪn", "n", "鸡", "bird"),
    ("chief", "tʃiːf", "n", "首领", "leader"),
    ("child", "tʃaɪld", "n", "孩子", "young person"),
    ("childhood", "ˈtʃaɪldhʊd", "n", "童年", "early years"),
    ("children", "ˈtʃɪldrən", "n", "孩子们", "young people"),
    ("china", "ˈtʃaɪnə", "n", "瓷器", "ceramic"),
    ("Chinese", "tʃaɪˈniːz", "adj", "中国的", "of China"),
    ("chip", "tʃɪp", "n", "薯片", "crisp"),
    ("chocolate", "ˈtʃɒklət", "n", "巧克力", "sweet"),
    ("choice", "tʃɔɪs", "n", "选择", "option"),
    ("choose", "tʃuːz", "v", "选择", "pick"),
    ("chopstick", "ˈtʃɒpstɪk", "n", "筷子", "eating tool"),
    ("Christmas", "ˈkrɪsməs", "n", "圣诞节", "holiday"),
    ("church", "tʃɜːrtʃ", "n", "教堂", "religious building"),
    ("cigarette", "ˌsɪɡəˈret", "n", "香烟", "tobacco roll"),
    ("cinema", "ˈsɪnəmə", "n", "电影院", "movie theater"),
    ("circle", "ˈsɜːrkl", "n", "圆圈", "round shape"),
    ("circumstance", "ˈsɜːrkəmstæns", "n", "情况", "condition"),
    ("citizen", "ˈsɪtɪzn", "n", "公民", "resident"),
    ("city", "ˈsɪti", "n", "城市", "large town"),
    ("civil", "ˈsɪvl", "adj", "公民的", "of citizens"),
    ("claim", "kleɪm", "v", "声称", "state"),
    ("clap", "klæp", "v", "拍手", "applaud"),
    ("class", "klɑːs", "n", "班级", "group of students"),
    ("classic", "ˈklæsɪk", "adj", "经典的", "traditional"),
    ("classical", "ˈklæsɪkl", "adj", "古典的", "traditional"),
    ("classmate", "ˈklɑːsmeɪt", "n", "同学", "fellow student"),
    ("classroom", "ˈklɑːsruːm", "n", "教室", "study room"),
    ("clean", "kliːn", "adj", "干净的", "not dirty"),
    ("clear", "klɪr", "adj", "清楚的", "obvious"),
    ("clearly", "ˈklɪrli", "adv", "清楚地", "obviously"),
    ("clerk", "klɜːrk", "n", "职员", "office worker"),
    ("clever", "ˈklevər", "adj", "聪明的", "smart"),
    ("click", "klɪk", "v", "点击", "press button"),
    ("climate", "ˈklaɪmət", "n", "气候", "weather pattern"),
    ("climb", "klaɪm", "v", "攀爬", "go up"),
    ("clinic", "ˈklɪnɪk", "n", "诊所", "medical center"),
    ("clock", "klɒk", "n", "时钟", "time device"),
    ("close", "kloʊz", "v", "关闭", "shut"),
    ("cloth", "klɔːθ", "n", "布", "fabric"),
    ("clothes", "kloʊðz", "n", "衣服", "clothing"),
    ("clothing", "ˈkloʊðɪŋ", "n", "服装", "clothes"),
    ("cloud", "klaʊd", "n", "云", "in sky"),
    ("cloudy", "ˈklaʊdi", "adj", "多云的", "full of clouds"),
    ("club", "klʌb", "n", "俱乐部", "organization"),
    ("coach", "koʊtʃ", "n", "教练", "trainer"),
    ("coal", "koʊl", "n", "煤", "fuel"),
    ("coast", "koʊst", "n", "海岸", "shoreline"),
    ("coat", "koʊt", "n", "外套", "jacket"),
    ("cock", "kɒk", "n", "公鸡", "male chicken"),
    ("code", "koʊd", "n", "代码", "system of symbols"),
    ("coffee", "ˈkɔːfi", "n", "咖啡", "drink"),
    ("coin", "kɔɪn", "n", "硬币", "metal money"),
    ("cold", "koʊld", "adj", "冷的", "not warm"),
    ("collar", "ˈkɒlər", "n", "衣领", "shirt part"),
    ("colleague", "ˈkɒliːɡ", "n", "同事", "coworker"),
    ("collect", "kəˈlekt", "v", "收集", "gather"),
    ("collection", "kəˈlekʃn", "n", "收藏", "group of items"),
    ("college", "ˈkɒlɪdʒ", "n", "学院", "higher education"),
    ("color", "ˈkʌlər", "n", "颜色", "hue"),
    ("column", "ˈkɒləm", "n", "专栏", "text section"),
    ("combine", "kəmˈbaɪn", "v", "结合", "join together"),
    ("come", "kʌm", "v", "来", "approach"),
    ("comfort", "ˈkʌmfərt", "n", "舒适", "ease"),
    ("comfortable", "ˈkʌmftəbl", "adj", "舒适的", "at ease"),
    ("command", "kəˈmɑːnd", "v", "命令", "order"),
    ("comment", "ˈkɒment", "n", "评论", "remark"),
    ("commercial", "kəˈmɜːrʃl", "adj", "商业的", "business"),
    ("commit", "kəˈmɪt", "v", "犯(罪)", "do wrong"),
    ("committee", "kəˈmɪti", "n", "委员会", "group"),
    ("common", "ˈkɒmən", "adj", "共同的", "shared"),
    ("communicate", "kəˈmjuːnɪkeɪt", "v", "交流", "share info"),
    ("communication", "kəˌmjuːnɪˈkeɪʃn", "n", "交流", "sharing info"),
    ("community", "kəˈmjuːnəti", "n", "社区", "neighborhood"),
    ("company", "ˈkʌmpəni", "n", "公司", "business"),
    ("compare", "kəmˈpeər", "v", "比较", "examine similarity"),
    ("compete", "kəmˈpiːt", "v", "竞争", "try to win"),
    ("competition", "ˌkɒmpəˈtɪʃn", "n", "竞争", "contest"),
    ("complain", "kəmˈpleɪn", "v", "抱怨", "express dissatisfaction"),
    ("complaint", "kəmˈpleɪnt", "n", "抱怨", "expression of dissatisfaction"),
    ("complete", "kəmˈpliːt", "adj", "完整的", "whole"),
    ("completely", "kəmˈpliːtli", "adv", "完全地", "totally"),
    ("complex", "ˈkɒmpleks", "adj", "复杂的", "complicated"),
    ("computer", "kəmˈpjuːtər", "n", "电脑", "computing machine"),
    ("concentrate", "ˈkɒnsntreɪt", "v", "集中", "focus"),
    ("concept", "ˈkɒnsept", "n", "概念", "idea"),
    ("concern", "kənˈsɜːrn", "n", "关心", "worry"),
    ("concerned", "kənˈsɜːrnd", "adj", "担心的", "worried"),
    ("concert", "ˈkɒnsərt", "n", "音乐会", "musical performance"),
    ("conclude", "kənˈkluːd", "v", "总结", "finish"),
    ("conclusion", "kənˈkluːʒn", "n", "结论", "ending"),
    ("condition", "kənˈdɪʃn", "n", "条件", "state"),
    ("conduct", "kənˈdʌkt", "v", "进行", "carry out"),
    ("conference", "ˈkɒnfərəns", "n", "会议", "meeting"),
    ("confidence", "ˈkɒnfɪdəns", "n", "信心", "self-assurance"),
    ("confident", "ˈkɒnfɪdənt", "adj", "自信的", "sure of oneself"),
    ("confirm", "kənˈfɜːrm", "v", "确认", "verify"),
    ("conflict", "ˈkɒnflɪkt", "n", "冲突", "disagreement"),
    ("confuse", "kənˈfjuːz", "v", "使困惑", "puzzle"),
    ("confused", "kənˈfjuːzd", "adj", "困惑的", "puzzled"),
    ("congratulate", "kənˈɡrætʃuleɪt", "v", "祝贺", "express joy"),
    ("connect", "kəˈnekt", "v", "连接", "join"),
    ("connection", "kəˈnekʃn", "n", "联系", "link"),
    ("conscious", "ˈkɒnʃəs", "adj", "有意识的", "aware"),
    ("consider", "kənˈsɪdər", "v", "考虑", "think about"),
    ("consideration", "kənˌsɪdəˈreɪʃn", "n", "考虑", "thought"),
    ("consist", "kənˈsɪst", "v", "由...组成", "be made of"),
    ("constant", "ˈkɒnstənt", "adj", "持续的", "continuous"),
    ("construct", "kənˈstrʌkt", "v", "建造", "build"),
    ("construction", "kənˈstrʌkʃn", "n", "建设", "building"),
    ("consume", "kənˈsjuːm", "v", "消费", "use up"),
    ("contact", "ˈkɒntækt", "n", "联系", "communication"),
    ("contain", "kənˈteɪn", "v", "包含", "hold"),
    ("container", "kənˈteɪnər", "n", "容器", "holder"),
    ("contemporary", "kənˈtempəreri", "adj", "当代的", "modern"),
    ("content", "ˈkɒntent", "n", "内容", "what is inside"),
    ("contest", "ˈkɒntest", "n", "比赛", "competition"),
    ("context", "ˈkɒntekst", "n", "背景", "setting"),
    ("continent", "ˈkɒntɪnənt", "n", "大陆", "land mass"),
    ("continue", "kənˈtɪnjuː", "v", "继续", "go on"),
    ("contract", "ˈkɒntrækt", "n", "合同", "agreement"),
    ("contribute", "kənˈtrɪbjuːt", "v", "贡献", "give"),
    ("contribution", "ˌkɒntrɪˈbjuːʃn", "n", "贡献", "giving"),
    ("control", "kənˈtroʊl", "v", "控制", "manage"),
    ("convenient", "kənˈviːniənt", "adj", "方便的", "easy to use"),
    ("conversation", "ˌkɒnvərˈseɪʃn", "n", "对话", "talk"),
    ("cook", "kʊk", "v", "烹饪", "prepare food"),
    ("cookie", "ˈkʊki", "n", "饼干", "sweet biscuit"),
    ("cool", "kuːl", "adj", "凉爽的", "slightly cold"),
    ("cooperate", "koʊˈɒpəreɪt", "v", "合作", "work together"),
    ("copy", "ˈkɒpi", "v", "复制", "duplicate"),
    ("corn", "kɔːrn", "n", "玉米", "grain"),
    ("corner", "ˈkɔːrnər", "n", "角落", "where edges meet"),
    ("correct", "kəˈrekt", "adj", "正确的", "right"),
    ("cost", "kɔːst", "n", "费用", "price"),
    ("couch", "kaʊtʃ", "n", "沙发", "sofa"),
    ("cough", "kɔːf", "v", "咳嗽", "expel air"),
    ("could", "kʊd", "v", "能(过去式)", "past of can"),
    ("count", "kaʊnt", "v", "数", "enumerate"),
    ("counter", "ˈkaʊntər", "n", "柜台", "service table"),
    ("country", "ˈkʌntri", "n", "国家", "nation"),
    ("countryside", "ˈkʌntrisaɪd", "n", "乡村", "rural area"),
    ("couple", "ˈkʌpl", "n", "一对", "two people"),
    ("courage", "ˈkɜːrɪdʒ", "n", "勇气", "bravery"),
    ("course", "kɔːrs", "n", "课程", "class"),
    ("court", "kɔːrt", "n", "法庭", "legal court"),
    ("cousin", "ˈkʌzn", "n", "表亲", "relative"),
    ("cover", "ˈkʌvər", "v", "覆盖", "put over"),
    ("cow", "kaʊ", "n", "奶牛", "farm animal"),
    ("crack", "kræk", "n", "裂缝", "break"),
    ("craft", "kræft", "n", "工艺", "skill"),
    ("crash", "kræʃ", "v", "碰撞", "collide"),
    ("crazy", "ˈkreɪzi", "adj", "疯狂的", "insane"),
    ("cream", "kriːm", "n", "奶油", "dairy product"),
    ("create", "kriˈeɪt", "v", "创造", "make"),
    ("creative", "kriˈeɪtɪv", "adj", "创造性的", "inventive"),
    ("creature", "ˈkriːtʃər", "n", "生物", "living thing"),
    ("credit", "ˈkredɪt", "n", "信用", "trust"),
    ("crime", "kraɪm", "n", "犯罪", "illegal act"),
    ("criminal", "ˈkrɪmɪnl", "n", "罪犯", "lawbreaker"),
    ("crisis", "ˈkraɪsɪs", "n", "危机", "emergency"),
    ("critical", "ˈkrɪtɪkl", "adj", "关键的", "crucial"),
    ("criticism", "ˈkrɪtɪsɪzəm", "n", "批评", "negative comment"),
    ("criticize", "ˈkrɪtɪsaɪz", "v", "批评", "find fault"),
    ("crop", "krɒp", "n", "庄稼", "farm produce"),
    ("cross", "krɔːs", "v", "穿过", "go across"),
    ("crowd", "kraʊd", "n", "人群", "many people"),
    ("crowded", "ˈkraʊdɪd", "adj", "拥挤的", "full of people"),
    ("cruel", "ˈkruːəl", "adj", "残忍的", "causing pain"),
    ("cry", "kraɪ", "v", "哭", "weep"),
    ("culture", "ˈkʌltʃər", "n", "文化", "way of life"),
    ("cup", "kʌp", "n", "杯子", "drinking vessel"),
    ("cupboard", "ˈkʌbərd", "n", "橱柜", "cabinet"),
    ("cure", "kjʊr", "v", "治愈", "heal"),
    ("curious", "ˈkjʊriəs", "adj", "好奇的", "eager to know"),
    ("currency", "ˈkɜːrənsi", "n", "货币", "money"),
    ("current", "ˈkɜːrənt", "adj", "当前的", "present"),
    ("curtain", "ˈkɜːrtn", "n", "窗帘", "window covering"),
    ("curve", "kɜːrv", "n", "曲线", "bent line"),
    ("custom", "ˈkʌstəm", "n", "习俗", "tradition"),
    ("customer", "ˈkʌstəmər", "n", "顾客", "buyer"),
    ("cut", "kʌt", "v", "切", "divide"),
    ("cycle", "ˈsaɪkl", "n", "循环", "series"),
    ("dad", "dæd", "n", "爸爸", "father"),
    ("daily", "ˈdeɪli", "adj", "每日的", "everyday"),
    ("damage", "ˈdæmɪdʒ", "n", "损害", "harm"),
    ("dance", "dæns", "v", "跳舞", "move to music"),
    ("dancer", "ˈdænsər", "n", "舞者", "one who dances"),
    ("danger", "ˈdeɪndʒər", "n", "危险", "risk"),
    ("dangerous", "ˈdeɪndʒərəs", "adj", "危险的", "risky"),
    ("dare", "deər", "v", "敢", "have courage"),
    ("dark", "dɑːrk", "adj", "黑暗的", "without light"),
    ("darkness", "ˈdɑːrknəs", "n", "黑暗", "absence of light"),
    ("data", "ˈdeɪtə", "n", "数据", "information"),
    ("date", "deɪt", "n", "日期", "day"),
    ("daughter", "ˈdɔːtər", "n", "女儿", "female child"),
    ("dawn", "dɔːn", "n", "黎明", "sunrise"),
    ("day", "deɪ", "n", "天", "24 hours"),
    ("dead", "ded", "adj", "死的", "not alive"),
    ("deadline", "ˈdedlaɪn", "n", "截止日期", "time limit"),
    ("deaf", "def", "adj", "聋的", "cannot hear"),
    ("deal", "diːl", "v", "处理", "handle"),
    ("dear", "dɪr", "adj", "亲爱的", "beloved"),
    ("death", "deθ", "n", "死亡", "end of life"),
    ("debate", "dɪˈbeɪt", "n", "辩论", "discussion"),
    ("debt", "det", "n", "债务", "money owed"),
    ("decade", "ˈdekeɪd", "n", "十年", "10 years"),
    ("decide", "dɪˈsaɪd", "v", "决定", "make choice"),
    ("decision", "dɪˈsɪʒn", "n", "决定", "choice"),
    ("declare", "dɪˈkleər", "v", "宣布", "announce"),
    ("decline", "dɪˈklaɪn", "v", "下降", "decrease"),
    ("decorate", "ˈdekəreɪt", "v", "装饰", "adorn"),
    ("decrease", "dɪˈkriːs", "v", "减少", "lessen"),
    ("deep", "diːp", "adj", "深的", "far down"),
    ("deeply", "ˈdiːpli", "adv", "深深地", "profoundly"),
    ("deer", "dɪr", "n", "鹿", "animal"),
    ("defeat", "dɪˈfiːt", "v", "打败", "beat"),
    ("defend", "dɪˈfend", "v", "防御", "protect"),
    ("define", "dɪˈfaɪn", "v", "定义", "explain meaning"),
    ("definite", "ˈdefɪnət", "adj", "明确的", "certain"),
    ("definitely", "ˈdefɪnətli", "adv", "肯定地", "certainly"),
    ("definition", "ˌdefɪˈnɪʃn", "n", "定义", "meaning"),
    ("degree", "dɪˈɡriː", "n", "度", "level"),
    ("delay", "dɪˈleɪ", "v", "延迟", "postpone"),
    ("delete", "dɪˈliːt", "v", "删除", "remove"),
    ("delicate", "ˈdelɪkət", "adj", "精致的", "fine"),
    ("delicious", "dɪˈlɪʃəs", "adj", "美味的", "tasty"),
    ("delight", "dɪˈlaɪt", "n", "高兴", "joy"),
    ("delighted", "dɪˈlaɪtɪd", "adj", "高兴的", "pleased"),
    ("deliver", "dɪˈlɪvər", "v", "递送", "bring"),
    ("delivery", "dɪˈlɪvəri", "n", "递送", "bringing"),
    ("demand", "dɪˈmænd", "v", "要求", "ask strongly"),
    ("democracy", "dɪˈmɒkrəsi", "n", "民主", "government by people"),
    ("demonstrate", "ˈdemənstreɪt", "v", "证明", "show"),
    ("dentist", "ˈdentɪst", "n", "牙医", "tooth doctor"),
    ("deny", "dɪˈnaɪ", "v", "否认", "refuse to accept"),
    ("department", "dɪˈpɑːrtmənt", "n", "部门", "division"),
    ("depend", "dɪˈpend", "v", "依靠", "rely on"),
    ("dependent", "dɪˈpendənt", "adj", "依赖的", "relying on"),
    ("deposit", "dɪˈpɒzɪt", "n", "存款", "money stored"),
    ("depress", "dɪˈpres", "v", "使沮丧", "make sad"),
    ("depressed", "dɪˈprest", "adj", "沮丧的", "sad"),
    ("depth", "depθ", "n", "深度", "how deep"),
    ("describe", "dɪˈskraɪb", "v", "描述", "tell about"),
    ("description", "dɪˈskrɪpʃn", "n", "描述", "account"),
    ("desert", "ˈdezərt", "n", "沙漠", "dry land"),
    ("deserve", "dɪˈzɜːrv", "v", "应得", "be worthy of"),
    ("design", "dɪˈzaɪn", "v", "设计", "plan"),
    ("designer", "dɪˈzaɪnər", "n", "设计师", "one who designs"),
    ("desire", "dɪˈzaɪər", "n", "渴望", "wish"),
    ("desk", "desk", "n", "书桌", "work table"),
    ("desperate", "ˈdespərət", "adj", "绝望的", "hopeless"),
    ("destination", "ˌdestɪˈneɪʃn", "n", "目的地", "end point"),
    ("destroy", "dɪˈstrɔɪ", "v", "破坏", "ruin"),
    ("destruction", "dɪˈstrʌkʃn", "n", "破坏", "ruining"),
    ("detail", "ˈdiːteɪl", "n", "细节", "small part"),
    ("determine", "dɪˈtɜːrmɪn", "v", "决定", "decide"),
    ("develop", "dɪˈveləp", "v", "发展", "grow"),
    ("development", "dɪˈveləpmənt", "n", "发展", "growth"),
    ("device", "dɪˈvaɪs", "n", "设备", "tool"),
    ("devote", "dɪˈvoʊt", "v", "奉献", "dedicate"),
    ("diagram", "ˈdaɪəɡræm", "n", "图表", "chart"),
    ("dialogue", "ˈdaɪəlɒɡ", "n", "对话", "conversation"),
    ("diamond", "ˈdaɪəmənd", "n", "钻石", "gem"),
    ("diary", "ˈdaɪəri", "n", "日记", "daily record"),
    ("dictionary", "ˈdɪkʃəneri", "n", "字典", "word book"),
    ("die", "daɪ", "v", "死亡", "stop living"),
    ("diet", "ˈdaɪət", "n", "饮食", "food eaten"),
    ("differ", "ˈdɪfər", "v", "不同", "be unlike"),
    ("difference", "ˈdɪfrəns", "n", "差异", "distinction"),
    ("different", "ˈdɪfrənt", "adj", "不同的", "not same"),
    ("difficult", "ˈdɪfɪkəlt", "adj", "困难的", "hard"),
    ("difficulty", "ˈdɪfɪkəlti", "n", "困难", "hardship"),
    ("dig", "dɪɡ", "v", "挖", "excavate"),
    ("digital", "ˈdɪdʒɪtl", "adj", "数字的", "electronic"),
    ("dinner", "ˈdɪnər", "n", "晚餐", "evening meal"),
    ("dinosaur", "ˈdaɪnəsɔːr", "n", "恐龙", "extinct reptile"),
    ("direct", "dəˈrekt", "adj", "直接的", "straight"),
    ("direction", "dəˈrekʃn", "n", "方向", "way"),
    ("director", "dəˈrektər", "n", "导演", "manager"),
    ("dirty", "ˈdɜːrti", "adj", "脏的", "not clean"),
    ("disable", "dɪsˈeɪbl", "v", "使残废", "make unable"),
    ("disabled", "dɪsˈeɪbld", "adj", "残疾的", "handicapped"),
    ("disadvantage", "ˌdɪsədˈvɑːntɪdʒ", "n", "缺点", "drawback"),
    ("disagree", "ˌdɪsəˈɡriː", "v", "不同意", "differ"),
    ("disappear", "ˌdɪsəˈpɪr", "v", "消失", "vanish"),
    ("disappoint", "ˌdɪsəˈpɔɪnt", "v", "使失望", "let down"),
    ("disappointed", "ˌdɪsəˈpɔɪntɪd", "adj", "失望的", "let down"),
    ("disappointment", "ˌdɪsəˈpɔɪntmənt", "n", "失望", "letdown"),
    ("disaster", "dɪˈzæstər", "n", "灾难", "catastrophe"),
    ("discipline", "ˈdɪsəplɪn", "n", "纪律", "order"),
    ("discount", "ˈdɪskaʊnt", "n", "折扣", "price reduction"),
    ("discover", "dɪˈskʌvər", "v", "发现", "find"),
    ("discovery", "dɪˈskʌvəri", "n", "发现", "finding"),
    ("discuss", "dɪˈskʌs", "v", "讨论", "talk about"),
    ("discussion", "dɪˈskʌʃn", "n", "讨论", "talk"),
    ("disease", "dɪˈziːz", "n", "疾病", "illness"),
    ("dish", "dɪʃ", "n", "盘子", "plate"),
    ("disk", "dɪsk", "n", "磁盘", "storage device"),
    ("dismiss", "dɪsˈmɪs", "v", "解散", "send away"),
    ("display", "dɪˈspleɪ", "v", "展示", "show"),
    ("distance", "ˈdɪstəns", "n", "距离", "space between"),
    ("distant", "ˈdɪstənt", "adj", "遥远的", "far away"),
    ("distinct", "dɪˈstɪŋkt", "adj", "独特的", "different"),
    ("distinguish", "dɪˈstɪŋɡwɪʃ", "v", "区分", "tell apart"),
    ("distribute", "dɪˈstrɪbjuːt", "v", "分配", "give out"),
    ("district", "ˈdɪstrɪkt", "n", "地区", "area"),
    ("disturb", "dɪˈstɜːrb", "v", "打扰", "interrupt"),
    ("dive", "daɪv", "v", "潜水", "plunge"),
    ("divide", "dɪˈvaɪd", "v", "分开", "separate"),
    ("division", "dɪˈvɪʒn", "n", "部门", "section"),
    ("divorce", "dɪˈvɔːrs", "n", "离婚", "end of marriage"),
    ("do", "duː", "v", "做", "perform"),
    ("doctor", "ˈdɒktər", "n", "医生", "physician"),
    ("document", "ˈdɒkjumənt", "n", "文件", "paper"),
    ("dog", "dɔːɡ", "n", "狗", "pet animal"),
    ("doll", "dɒl", "n", "玩偶", "toy figure"),
    ("dollar", "ˈdɒlər", "n", "美元", "currency"),
    ("dolphin", "ˈdɒlfɪn", "n", "海豚", "sea mammal"),
    ("domestic", "dəˈmestɪk", "adj", "国内的", "home"),
    ("donate", "ˈdoʊneɪt", "v", "捐赠", "give"),
    ("donation", "doʊˈneɪʃn", "n", "捐赠", "gift"),
    ("door", "dɔːr", "n", "门", "entrance"),
    ("dot", "dɒt", "n", "点", "small mark"),
    ("double", "ˈdʌbl", "adj", "双倍的", "twice"),
    ("doubt", "daʊt", "n", "怀疑", "uncertainty"),
    ("down", "daʊn", "adv", "向下", "below"),
    ("download", "ˈdaʊnloʊd", "v", "下载", "transfer data"),
    ("downstairs", "ˌdaʊnˈsteərz", "adv", "在楼下", "on lower floor"),
    ("downtown", "ˌdaʊnˈtaʊn", "n", "市中心", "city center"),
    ("dozen", "ˈdʌzn", "n", "一打", "twelve"),
    ("draft", "dræft", "n", "草稿", "rough version"),
    ("drag", "dræɡ", "v", "拖", "pull"),
    ("dragon", "ˈdræɡən", "n", "龙", "mythical creature"),
    ("drama", "ˈdrɑːmə", "n", "戏剧", "play"),
    ("dramatic", "drəˈmætɪk", "adj", "戏剧性的", "theatrical"),
    ("draw", "drɔː", "v", "画", "make picture"),
    ("drawer", "drɔːr", "n", "抽屉", "sliding box"),
    ("drawing", "ˈdrɔːɪŋ", "n", "图画", "picture"),
    ("dream", "driːm", "n", "梦", "vision"),
    ("dress", "dres", "n", "连衣裙", "clothing"),
    ("drill", "drɪl", "n", "训练", "practice"),
    ("drink", "drɪŋk", "v", "喝", "consume liquid"),
    ("drive", "draɪv", "v", "驾驶", "operate vehicle"),
    ("driver", "ˈdraɪvər", "n", "司机", "one who drives"),
    ("drop", "drɒp", "v", "落下", "fall"),
    ("drought", "draʊt", "n", "干旱", "lack of rain"),
    ("drown", "draʊn", "v", "淹死", "die in water"),
    ("drug", "drʌɡ", "n", "药物", "medicine"),
    ("drum", "drʌm", "n", "鼓", "percussion"),
    ("drunk", "drʌŋk", "adj", "醉的", "intoxicated"),
    ("dry", "draɪ", "adj", "干的", "not wet"),
    ("duck", "dʌk", "n", "鸭子", "water bird"),
    ("due", "djuː", "adj", "到期的", "expected"),
    ("dull", "dʌl", "adj", "无聊的", "boring"),
    ("dump", "dʌmp", "v", "倾倒", "throw away"),
    ("during", "ˈdjʊərɪŋ", "prep", "在...期间", "throughout"),
    ("dust", "dʌst", "n", "灰尘", "fine particles"),
    ("dusty", "ˈdʌsti", "adj", "多灰尘的", "covered in dust"),
    ("duty", "ˈdjuːti", "n", "责任", "obligation"),
    ("dying", "ˈdaɪɪŋ", "adj", "垂死的", "about to die"),
    ("dynamic", "daɪˈnæmɪk", "adj", "动态的", "active"),
]

# 由于词汇量大，这里只展示前500个词，完整版本需要更多数据
# 其余词汇按相同格式添加...

def generate_wordlist(words, level, prefix, output_file):
    """生成词库文件"""
    word_list = []
    for i, (word, phonetic, pos, zh, en) in enumerate(words, 1):
        word_list.append({
            "id": f"{prefix}_{i:03d}",
            "word": word,
            "phonetic": phonetic,
            "pos": pos,
            "meaning": {"zh": zh, "en": en}
        })

    data = {
        "level": level,
        "totalWords": len(word_list),
        "version": 1,
        "words": word_list
    }

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"已生成 {output_file}，共 {len(word_list)} 个单词")
    return len(word_list)

if __name__ == "__main__":
    # 生成初中词库
    junior_file = os.path.join(OUTPUT_DIR, 'junior.json')
    generate_wordlist(JUNIOR_WORDS, "Junior", "jun", junior_file)
